export const CURSOS_LECTIVOS_LOAD = 'CURSOS_LECTIVOS_LOAD'
export const CURSOS_LECTIVOS_LOAD_CALENDARS = 'CURSOS_LECTIVOS_LOAD_CALENDARS'
export const CURSOS_LECTIVOS_SET_ACTIVE = 'CURSOS_LECTIVOS_SET_ACTIVE'
export const CURSOS_LECTIVOS_SET_CALENDAR_ACTIVE =
  'CURSOS_LECTIVOS_SET_CALENDAR_ACTIVE'
export const CURSOS_LECTIVOS_CLEAR_CALENDARS = 'CURSOS_LECTIVOS_CLEAR_CALENDARS'
export const CURSOS_LECTIVOS_CHANGE_STATE = 'CURSOS_LECTIVOS_CHANGE_STATE'
export const CURSOS_LECTIVOS_CALENDARIOS_CHANGE_STATE =
  'CURSOS_LECTIVOS_CALENDARIOS_CHANGE_STATE'
