export const LOAD_ASIGNATURAS = 'LOAD_ASIGNATURAS'
export const LOAD_ASIGNATURAS_TIPOS = 'LOAD_ASIGNATURAS_TIPOS'
export const LOAD_ASIGNATURAS_OPTIONS = 'LOAD_ASIGNATURAS_OPTIONS'
export const LOAD_ASIGNATURAS_PAGINATED = 'LOAD_ASIGNATURAS_PAGINATED'
export const LOAD_TIPOS_EVALUACIONES = 'LOAD_TIPOS_EVALUACIONES'
// export const LOAD_ASIGNATURAS_
