export const CANTONES_LOAD = 'CANTONES_LOAD'
export const CANTONES_TEMPORAL_LOAD = 'CANTONES_TEMPORAL_LOAD'
export const CANTONES_ERROR = 'CANTONES_ERROR'
export const CANTONES_LOADING = 'CANTONES_LOADING'
