export const DISTRITOS_LOAD = 'DISTRITOS_LOAD'
export const DISTRITOS_TEMPORALES_LOAD = 'DISTRITOS_TEMPORALES_LOAD'
export const DISTRITOS_ERROR = 'DISTRITOS_ERROR'
export const DISTRITOS_LOADING = 'DISTRITOS_LOADING'
