/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE'
export const LOGIN_TIME = 'LOGIN_TIME'

/* AUTH */
export const SET_USER_INSTITUTION = 'SET_USER_INSTITUTION'
export const SET_PERIODO_LECTIVO_BY_INSTITUTION = 'SET_PERIODO_LECTIVO_BY_INSTITUTION'
export const AUTH_LOAD_INSTITUTIONS = 'AUTH_LOAD_INSTITUTIONS'
export const AUTH_LOADING = 'AUTH_LOADING'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_TOKEN_STORAGE = 'AUTH_TOKEN_STORAGE'
export const REGISTER_USER_LOADING = 'REGISTER_USER_LOADING'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const CONFIRM_FORGOT_PASSWORD = 'CONFIRM_FORGOT_PASSWORD'
export const GET_ROLE = 'GET_ROLE'
export const ROLE_ERROR = 'ROLE_ERROR'
export const CREATE_PASSWORD = 'CREATE_PASSWORD'
export const CREATE_PASSWORD_ERROR = 'CREATE_PASSWORD_ERROR'
export const SERVER_ERROR = 'SERVER_ERROR'
export const SEREVER_UNAUTHORIZED = 'SEREVER_UNAUTHORIZED'
export const LOAD_CURRENTDIRECTOR = 'LOAD_CURRENTDIRECTOR'
export const LOAD_CURRENTDIRECTOR_ERROR = 'LOAD_CURRENTDIRECTOR'
export const API_VERSION = 'API_VERSION'
export const LOAD_ACCESS_ROLES = 'LOAD_ACCESS_ROLES'
export const LOAD_CURRENT_ACCESS_ROLE = 'LOAD_CURRENT_ACCESS_ROLE'
export const LOAD_USER_DATA = 'LOAD_USER_DATA'
export const CLEAR_CURRENT_INSTITUTION = 'CLEAR_CURRENT_INSTITUTION'

/* TEST LIST */
export const TEST_LIST_LOAD = 'TEST_LIST_LOAD'
export const TEST_LIST_LOADING = 'TEST_LIST_LOADING'
export const TEST_LIST_FAILURE = 'TEST_LIST_FAILURE'

/* TEST */
export const TEST_LOAD = 'TEST_LOAD'
export const TEST_LOADING = 'TEST_LOADING'
export const TEST_FAILURE = 'TEST_FAILURE'

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES'
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME'
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU'
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES'
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS = 'MENU_CHANGE_HAS_SUB_ITEM_STATUS'
export const SET_MENU_STATE = 'SET_MENU_STATE'
export const TOGGLE_MENU_STATE = 'TOGGLE_MENU_STATE'

export const LOAD_ACTIVE_YEAR = 'LOAD_ACTIVE_YEAR'
export const LOAD_ACTIVE_YEARS = 'LOAD_ACTIVE_YEARS'
export const LOAD_ROLES_PERMISOS = 'LOAD_ROLES_PERMISOS'
export const AUTH_CLEAR_FAILURE = 'AUTH_CLEAR_FAILURE'

export * from './menu/actions'
export * from './settings/actions'
export * from './auth/actions.ts'
