enum types {
  GET_SCORES = 'GET_SCORES',
  QUALIFY_STUDENT = 'QUALIFY_STUDENT',
  LOADING_SCORES = 'LOADING_SCORES',
  UPDATE_QUALIFY = 'UPDATE_QUALIFY',
  UPDATE_SUBJECT_GROUP_JSON = 'UPDATE_SUBJECT_GROUP_JSON',
  REMOVE_SCORES_BY_SUBJECT_GROUP = 'REMOVE_SCORES_BY_SUBJECT_GROUP',
  LOAD_SCORES_BITACORA = 'LOAD_SCORES_BITACORA'
}

export default types
