enum types {
  UPDATE_SUBJECT_GROUP_ENROLLED_STUDENT = 'UPDATE_SUBJECT_GROUP_ENROLLED_STUDENT',
  CREATE_MULTIPLE_SUBJECT_GROUP_ENROLLED_STUDENT = 'ADD_SUBJECT_GROUP_ENROLLED_STUDENT',
}

export default types
