export const POBLADOS_LOAD = 'POBLADOS_LOAD'
export const POBLADOS_TEMPORAL_LOAD = 'POBLADOS_TEMPORAL_LOAD'
export const POBLADOS_ERROR = 'POBLADOS_ERROR'
export const POBLADOS_LOADING = 'POBLADOS_LOADING'
