enum types {
  GET_PAGINATE_PROFESSORS = 'GET_PAGINATE_PROFESSORS',
  LOADING_PROFESSORS = 'LOADING_PROFESSORS',
  GET_ALL_PROFESSORS = 'GET_ALL_PROFESSORS',
  GET_PROFESSORS_WITHOUT_SCHEDULE = 'GET_PROFESSORS_WITHOUT_SCHEDULE',
  GET_PROFESSORS_BY_INSTITUTION_ID = 'GET_PROFESSORS_BY_INSTITUTION_ID',
}

export default types
